# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sd9server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sd9',
            old_name='aux10Names',
            new_name='inputNames',
        ),
        migrations.RemoveField(
            model_name='sd9',
            name='aux11Names',
        ),
        migrations.RemoveField(
            model_name='sd9',
            name='aux12Names',
        ),
        migrations.RemoveField(
            model_name='sd9',
            name='aux1Names',
        ),
        migrations.RemoveField(
            model_name='sd9',
            name='aux2Names',
        ),
        migrations.RemoveField(
            model_name='sd9',
            name='aux3Names',
        ),
        migrations.RemoveField(
            model_name='sd9',
            name='aux4Names',
        ),
        migrations.RemoveField(
            model_name='sd9',
            name='aux5Names',
        ),
        migrations.RemoveField(
            model_name='sd9',
            name='aux6Names',
        ),
        migrations.RemoveField(
            model_name='sd9',
            name='aux7Names',
        ),
        migrations.RemoveField(
            model_name='sd9',
            name='aux8Names',
        ),
        migrations.RemoveField(
            model_name='sd9',
            name='aux9Names',
        ),
    ]
