# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd9server', '0002_auto_20160913_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sd9',
            name='aux10Values',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux11Values',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux12Values',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux1Values',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux2Values',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux3Values',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux4Values',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux5Values',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux6Values',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux7Values',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux8Values',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux9Values',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='inputNames',
            field=models.CharField(max_length=500),
        ),
    ]
