# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd9server', '0003_auto_20160913_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='sd9',
            name='auxNames',
            field=models.CharField(default='["","","","","","","","","","","",""]', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux10Values',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux11Values',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux12Values',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux1Values',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux2Values',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux3Values',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux4Values',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux5Values',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux6Values',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux7Values',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux8Values',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='aux9Values',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sd9',
            name='inputNames',
            field=models.CharField(max_length=1000),
        ),
    ]
